name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup build environment
      run: |
        sudo apt-get update && sudo apt-get install -y \
            build-essential \
            cmake \
            devscripts \
            debhelper \
            dh-make \
            fakeroot \
            lintian \
            pbuilder

        wget -q https://github.com/casey/just/releases/download/1.41.0/just-1.41.0-x86_64-unknown-linux-musl.tar.gz \
            && tar -xzf just-1.41.0-x86_64-unknown-linux-musl.tar.gz -C /tmp just \
            && sudo mv /tmp/just /usr/local/bin/just \
            && rm just-1.41.0-x86_64-unknown-linux-musl.tar.gz
      
    - name: Build project
      run: just pkg
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trigger-package
        path: out/libtrigger.deb
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: trigger-package
        path: artifacts
        
    - name: Create Release Assets
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        mv artifacts/libtrigger.deb artifacts/trigger-${VERSION}.deb
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/trigger-*.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 